name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy